#!/bin/sh
#
# Load aliases and functions

# Avoid weird aliases on public servers
unalias -a

# Generate a SSH key dynamically in the correct directory
gen() {
      if [ "$1" ]; then
         ssh-keygen -t ed25519 -C "$EMAIL" -f "$XDG_DATA_HOME/ssh/keys/$1"
      else
         echo "You must provide a filename"
      fi
}

# Verify that a package is installed
have() { type "$1" > /dev/null 2>&1; }

# Add colors in man pages
man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}

# Alias respecting programs.
alias electrum='electrum --dir $XDG_CONFIG_HOME/electrum'
alias mbsync='mbsync -c $XDG_CONFIG_HOME/isync/mbsyncrc'
alias newsboat='newsboat -u $XDG_CONFIG_HOME/newsboat/urls'
alias ssh='ssh -F $XDG_CONFIG_HOME/ssh/config'
alias startx='startx $XDG_CONFIG_HOME/X11/xinitrc'
alias tmux='tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf'

# Convertions
if have libreoffice; then
    alias doc2pdf='libreoffice --headless --convert-to pdf *.docx'
    alias odt2pdf='libreoffice --headless --convert-to pdf *.odt'
fi

# Display
if have exa; then
    alias a='exa -al'
fi

# Docker
if have docker; then
    alias dke='docker exec -it'
    alias dkr='docker run -d -P --name'
fi

alias moc='mu cfind --format=org-contact'

# GNU Emacs
if have emacs; then
    alias ec="emacsclient -cn"
fi

# GPG
alias mygpg='gpg --list-secret-keys --keyid-format=LONG karolos.triantafyllou@gmail.com'
alias gpgC='gpg --recipient $GPGKEY --encrypt'
alias gpgDP='gpg --delete-keys'
alias gpgDS='gpg --delete-secret-keys'
alias gpgE='gpg --edit-key'
alias gpgG='gpg --full-generate-key'
alias gpgLP='gpg --list-keys'
alias gpgLS='gpg -K'
alias gpgR='gpg-connect-agent reloadagent /bye'

# LaTeX
alias xelatex='xelatex --shell-escape'

# Navigation
alias d='cd $XDG_DATA_HOME/docker/'
alias g='cd $XDG_DATA_HOME/git/'
alias q='cd $XDG_DATA_HOME/qemu/'
alias n='cd $XDG_DATA_HOME/notebooks/'

# pacman
alias inpac='pacman -Qmq | sort'
alias mymakepkg='makepkg -sirc'

# systemctl
if have systemctl && [[ -d /run/systemd/system ]]; then
	alias enable='sudo systemctl enable'
	alias disable='sudo systemctl disable'
	alias y='systemctl'

	reload()  { sudo systemctl reload "$@";  _status "$@"; }
	restart() { sudo systemctl restart "$@"; _status "$@"; }
	start()   { sudo systemctl start "$@";   _status "$@"; }
	stop()    { sudo systemctl stop "$@";    _status "$@"; }
	_status() { sudo SYSTEMD_PAGER='cat' systemctl status -a -n0 "$@"; }
	status()  { SYSTEMD_PAGER='cat' systemctl status -a "$@"; }

    alias services='systemctl list-unit-files | grep enabled && systemctl --user list-unit-files | grep enabled'
	alias list='systemctl list-units -t path,service,socket --no-legend'
	alias userctl='systemctl --user'
	alias u='systemctl --user'

	ustart()   { userctl start "$@";   userctl status -a "$@"; }
	ustop()    { userctl stop "$@";    userctl status -a "$@"; }
	urestart() { userctl restart "$@"; userctl status -a "$@"; }
	ureload()  { userctl reload "$@";  userctl status -a "$@"; }

	alias ulist='userctl list-units -t path,service,socket --no-legend'
fi

# top
alias top_cpu='top -b -o +%CPU | head -n 22'
alias top_mem='top -b -o +%MEM | head -n 22'

# tmux
alias ta='tmux attach -t'
alias tad='tmux attach -d -t'
alias tk='tmux kill-session -t'
alias tka='tmux kill-server'
alias tl='tmux list-sessions'
alias ts='tmux new-session -s'

# Translation
if have trans; then
    alias de='trans --brief :de'
    alias en='trans --brief :en'
    alias fr='trans --brief :fr'
    alias it='trans --brief :it'
    alias nl='trans --brief :nl'
fi

# youtube-dl
if have youtube-dl; then
    alias yeam='yt-dlp --embed-thumbnail --extract-audio --audio-format m4a --audio-quality 0 -o "~/Music/%(title)s.%(ext)s"'
fi

# Use `arecord -l` to list recording cards or devices.
if have ffmpeg; then
	alias rec="ffmpeg -f alsa -i hw:0 ~/Audio/Records/$(date +'%Y-%m-%d-%H%M%S').mp3"
fi

if have fzf; then
    o() { local f; f=$(ls|fzf); [[ ! -z "$f" ]] && ec "$f"; }
fi

# color picker
if have grim; then
    alias cpick='grim -g "$(slurp -p)" -t ppm - | convert - -format "%[pixel:p{0,0}]" txt:-'
fi

# xbps
alias pu='paru -Syu'
alias pi='sudo pacman -S'
alias pq='sudo pacman -Ss'
alias pr='sudo pacman -Rs'
alias pi='paru -S'

# Programming
alias gtp='cd ~/Programming/cpp'

# Update Pacman mirror list.
if have reflector; then
    alias reflect='sudo reflector --latest 50 --verbose --protocol http --protocol https --sort rate --download-timeout 10 --save /etc/pacman.d/mirrorlist'
fi

alias log="journalctl -u NetworkManager -b -n 1000"
alias weather='http --print=b wttr.in'


alias obs="VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_pro_icd64.json:/usr/share/vulkan/icd.d/amd_pro_icd32.json obs"
